/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hashgraph_constants.h"

namespace hashgraph { namespace message {

const hashgraphConstants g_hashgraph_constants;

hashgraphConstants::hashgraphConstants() {
}

}} // namespace

