/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hashgraph_CONSTANTS_H
#define hashgraph_CONSTANTS_H

#include "hashgraph_types.h"

namespace hashgraph { namespace message {

class hashgraphConstants {
 public:
  hashgraphConstants();

};

extern const hashgraphConstants g_hashgraph_constants;

}} // namespace

#endif
